import json
from pathlib import Path
from typing import Any

ORDERS = { "88213": {"status": "shipped", "amount": 1200.0}}

def get_order(order_id: str) -> dict:
    """Return order information for a known order."""

    if not order_id:
        raise ValueError("order_id is required")

    order = ORDERS.get(order_id)

    if order is None:
        return {
            "status": "not_found",
            "order_id": order_id
        }

    return {
        "status": "completed",
        "order_id": order_id,
        "order": order
    }

TOOL_REGISTRY = {"get_order": get_order}

def vulnerable_execute(tool_name: str, arguments: dict[str, Any]) -> dict:
    """ Current executor behavior.
    Weakness:
    The tool name is not validated before accessing TOOL_REGISTRY.
    An unsupported tool therefore raises KeyError. """

    tool = TOOL_REGISTRY[tool_name]

    return tool(**arguments)

def reproduce_finding() -> dict:
    """ Reproduce the unsupported-tool weakness and return evidence. """

    finding = {
        "area": "tool execution",
        "severity": "high",
        "finding": "Executor does not validate tool names before execution.",
        "impact": "An unsupported tool generated by the planner can cause the execution flow to fail."
    }

    try:
        vulnerable_execute(tool_name="delete_order", arguments={"order_id": "88213"})

        finding["reproduced"] = False
        finding["evidence"] = "Weakness was not reproduced."

    except KeyError as error:
        finding["reproduced"] = True
        finding["evidence"] = f"Unsupported tool caused KeyError: {error}"

    return finding

def save_evidence(finding: dict) -> Path:
    output_dir = Path("outputs")
    output_dir.mkdir(exist_ok=True)

    output_path = output_dir / "finding_before.json"

    with output_path.open("w", encoding="utf-8") as file:
        json.dump(finding, file, indent=2)

    return output_path

if __name__ == "__main__":

    print("Finding Reproduction")
    print("-" * 50)

    valid_result = vulnerable_execute(tool_name="get_order", arguments={"order_id": "88213"})

    print("\nValid tool execution:")
    print(valid_result)

    finding = reproduce_finding()

    print("\nFinding:")
    print(f"Area: {finding['area']}")
    print(f"Severity: {finding['severity']}")
    print(f"Finding: {finding['finding']}")
    print(f"Impact: {finding['impact']}")
    print(f"Reproduced: {finding['reproduced']}")
    print(f"Evidence: {finding['evidence']}")

    output_path = save_evidence(finding)

    print(f"\nEvidence saved to: {output_path}")