import json
import os
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

OUTPUT_DIR = Path("outputs")

def load_json_file(filename: str) -> dict | list:
    """Load a JSON evidence file from outputs."""

    path = OUTPUT_DIR / filename

    if not path.exists():
        raise FileNotFoundError(f"Required evidence file not found: {path}")

    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def load_project_evidence() -> dict:
    """Load evidence generated by Tasks 1 to 4."""

    return {"architecture_inventory": load_json_file("architecture_inventory.json"),
        "finding_before": load_json_file("finding_before.json"),
        "finding_after": load_json_file("finding_after.json"),
        "operational_risk_register": load_json_file("operational_risk_register.json"),
    }


def validate_evidence(evidence: dict) -> bool:
    """Ensure all required evidence sections are available."""

    required_sections = {"architecture_inventory", "finding_before", "finding_after", "operational_risk_register"}
    missing = required_sections - set(evidence)

    if missing:
        raise ValueError(f"Missing review evidence: {sorted(missing)}")

    if not evidence["architecture_inventory"]:
        raise ValueError("Architecture inventory cannot be empty.")

    return True

def build_review_prompt(evidence: dict) -> str:
    """Build the prompt using only verified project evidence."""

    return f"""You are preparing a concise engineering review for an AI agent architecture.

Use ONLY the project evidence provided below.
Do not invent vulnerabilities, controls, metrics, or fixes.

The review must contain these sections:
1. Architecture Summary
2. Primary Finding
3. Impact
4. Remediation
5. Before vs After
6. Residual Risks
7. Recommended Next Action
Keep the report clear, technical, and concise.

PROJECT EVIDENCE:
Architecture Inventory: {json.dumps(evidence["architecture_inventory"], indent=2)}
Finding Before Fix: {json.dumps(evidence["finding_before"], indent=2)}
Finding After Fix: {json.dumps(evidence["finding_after"], indent=2)}
Operational Risk Register: {json.dumps(evidence["operational_risk_register"], indent=2)} """


def call_llm(prompt: str) -> str:
    """Generate the final review using OpenRouter."""

    api_key = os.getenv("API_KEY")
    base_url = os.getenv("BASE_URL")
    model_name = os.getenv("MODEL_NAME")

    if not api_key:
        raise ValueError("API_KEY is missing from environment.")

    if not base_url:
        raise ValueError("BASE_URL is missing from environment.")

    if not model_name:
        raise ValueError("MODEL_NAME is missing from environment.")

    client = OpenAI(api_key=api_key, base_url=base_url)

    response = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": "You are an AI systems engineering reviewer. Report only what is supported by the supplied evidence."},
            {"role": "user", "content": prompt},
        ], temperature=0.2, timeout=30.0)

    return response.choices[0].message.content.strip()


def create_review_report() -> dict:
    """Load evidence, validate it, and generate the final review."""

    evidence = load_project_evidence()

    validate_evidence(evidence)

    prompt = build_review_prompt(evidence)

    report_text = call_llm(prompt)

    if not report_text:
        raise ValueError("LLM returned an empty review report.")

    return {
        "status": "completed",
        "report": report_text,
        "evidence_sources": ["architecture_inventory.json", "finding_before.json", "finding_after.json", "operational_risk_register.json"],
    }

def save_report(report: dict) -> tuple[Path, Path]:
    """Save both human-readable and structured report evidence."""

    OUTPUT_DIR.mkdir(exist_ok=True)

    text_path = OUTPUT_DIR / "final_review_report.txt"
    json_path = OUTPUT_DIR / "final_review_report.json"

    with text_path.open("w", encoding="utf-8") as file:
        file.write(report["report"])

    with json_path.open("w", encoding="utf-8") as file:
        json.dump(report, file, indent=2)

    return text_path, json_path

if __name__ == "__main__":

    print("AI Agent Architecture Review")
    print("-" * 60)

    report = create_review_report()

    print("\nFinal Engineering Review\n")
    print(report["report"])

    text_path, json_path = save_report(report)

    print("\nReport saved to:")
    print(f"- {text_path}")
    print(f"- {json_path}")